### ISSUE TITLE
How set 'index, nofollow' only one page?

### ISSUE THREAD

**Issue by zswilhelm** [harlan-zw/nuxt-simple-robots#1]
### Details

`export default defineNuxtConfig({
  routeRules: {
    // disable indexing to all routes in /secret/
    '/secret/**': { index: false },
  }
})`

all /secret/ urls are index, follow
the index parameter is boolean:
index: false --> noindex, nofollow,
index:true --> index, follow

How to set the 'index, nofollow' parameter for only one page?
Example:
/secret/ - index, nofollow
/secret/other - index, follow

**Comment by harlan-zw** [comment]
Hey @zswilhelm 

I've updated the example in the read me for this use case. You would define your config like

```ts
export default defineNuxtConfig({
  routeRules: {
    // disable indexing to all routes in /secret/
    '/secret/**': { index: false },
    // add exceptions for individual routes
    '/secret/visible': { index: true },
  }
})
```

In version 0.2.0, I've added support for a `robots` route rule, which lets you set the robots using a string, as I noticed you weren't using the default values.

```ts
export default defineNuxtConfig({
  routeRules: {
    // disable indexing to all routes in /secret/
    '/secret/**': { robots: 'noindex, nofollow' },
    // add exceptions for individual routes
    '/secret/visible': { robots: 'index, follow' },
  }
})
```

Let me know if you have any issues with it
