### ISSUE TITLE
Set x-robots-tag header also for static files

### ISSUE THREAD

**Issue by tobiasdiez** [harlan-zw/nuxt-simple-robots#11]
### Clear and concise description of the problem

Currently, the [server middleware](https://github.com/harlan-zw/nuxt-simple-robots/blob/main/src/runtime/server/robots-middleware.ts) is only invoked for, well, files that are processed on the server. However, static files (or statically generated ones) do not get the correct header applied. For this, the nitro presets would need to set the correct header on the corresponding routes.

### Suggested solution

As proposed by Daniel in https://github.com/unjs/nitro/issues/1087#issuecomment-1530983409, the robots module should simply convert the `robots` option to the correct route `headers`, which is then applied by nitro.

**Comment by harlan-zw** [comment]
Hey @tobiasdiez, thanks for the suggestion.

I have added this feature in 2.3.0 but it will only be useful for static files and specific environments which create a headers config with the deployment provider (Azure, Netlify). It doesn't do anything for dev or node-server.

**Comment by tobiasdiez** [comment]
A bit late, but thanks a lot for your work on this (and the module in general)!
