### ISSUE TITLE
The nuxt-site-config link does not exist

### ISSUE THREAD

**Issue by 9haroon** [harlan-zw/nuxt-simple-robots#16]
https://github.com/harlan-zw/nuxt-simple-robots/blob/9456672c4cf6e911bf2aec887da6547790266d17/src/module.ts#L130

**Comment by harlan-zw** [comment]
Hey @moonrinnn, thanks for the issue.

This package is currently being finalized and will be released within the next couple of days.

If you have any questions on it in the mean time, let me know :)

**Comment by harlan-zw** [comment]
Published now :+1:
