### ISSUE TITLE
Lighthouse test complains: `robots.txt is not valid/Invalid sitemap url`

### ISSUE THREAD

**Issue by madebyfabian** [harlan-zw/nuxt-simple-robots#2]
### Describe the bug

I was running a lighthouse text with a page using `nuxt-seo-kit`. The generated `robots.txt`:
```
User-agent: *

Sitemap: /sitemap.xml
```

According to the sitemaps.org docs it must be a full relative url. https://www.sitemaps.org/protocol.html#submit_robots

![Bildschirm­foto 2023-02-01 um 20 43 22](https://user-images.githubusercontent.com/32813692/216146793-523c863f-a803-4c2c-bb2f-924d538ee187.jpg)

### Reproduction

Blank Project with nuxt-seo-kit

### System Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @madebyfabian 

Thanks for the issue. I believe this is because you haven't provided a siteUrl for nuxt-seo-kit?

I'll disable the sitemap injection if it's not provided and maybe throw a warning

**Comment by madebyfabian** [comment]
@harlan-zw Interestingly, I've done this:

```
export default defineNuxtConfig({
	extends: ['nuxt-seo-kit'],
	runtimeConfig: {
		public: {
			// nuxt-seo-kit
			siteUrl: '',
		},
	},
})
```

which is valid nuxt syntax to leave an empty space and let the env var `NUXT_PUBLIC_SITE_URL` be injected into it. But somhow nuxt doesn't do that on generation, so 

```
export default defineNuxtConfig({
	extends: ['nuxt-seo-kit'],
	runtimeConfig: {
		public: {
			// nuxt-seo-kit
			siteUrl: process.env.NUXT_PUBLIC_SITE_URL,
		},
	},
})
```

everything works again, and the `robots.txt` is valid again.

Thanks for updating the module to include a warning!

**Comment by harlan-zw** [comment]
> @harlan-zw Interestingly, I've done this:
> 
> ```
> export default defineNuxtConfig({
> 	extends: ['nuxt-seo-kit'],
> 	runtimeConfig: {
> 		public: {
> 			// nuxt-seo-kit
> 			siteUrl: '',
> 		},
> 	},
> })
> ```
> 
> which is valid nuxt syntax to leave an empty space and let the env var `NUXT_PUBLIC_SITE_URL` be injected into it. But somhow nuxt doesn't do that on generation, so
> 
> ```
> export default defineNuxtConfig({
> 	extends: ['nuxt-seo-kit'],
> 	runtimeConfig: {
> 		public: {
> 			// nuxt-seo-kit
> 			siteUrl: process.env.NUXT_PUBLIC_SITE_URL,
> 		},
> 	},
> })
> ```
> 
> everything works again, and the `robots.txt` is valid again.
> 
> Thanks for updating the module to include a warning!

Ye I noticed the behavior is a little weird. I'll update the docs to point people to this sort of syntax

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    siteUrl: process.env.NUXT_PUBLIC_SITE_URL || 'https://example.com',
  },
})
```

**Comment by madebyfabian** [comment]
@harlan-zw Yeah, happens only in some cases. Will investigate and create an issue in the nuxt/nuxt repo if that's a nuxt bug.

**Comment by madebyfabian** [comment]
Interesting, so it's not an issue with nuxt per-se, since this does work fine with all other variables. But it seems that the plugin cannot catch the injection, because it maybe happens later in the process, and therefore the empty string syntax is not working. Not sure if this is something you can have an impact on, or something module authors have to live with, that users cannot use the empty-string syntax for runtimeConfig entries that are used within a module.

Check out a reprod: https://stackblitz.com/edit/github-qrbpqh?file=app.vue,nuxt.config.ts,.env

**Comment by madebyfabian** [comment]
FYI: https://github.com/nuxt/nuxt/issues/18692
