### ISSUE TITLE
Disallow and Allow Options don't work into nuxt.config file

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-robots#21]
### Describe the bug

Even if you set `allow` or `disallow` options of `robots` into nuxt.config.js file, url are not added into robots.txt.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gmcuhd?file=nuxt.config.ts

### System / Nuxt Info

```Shell
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.8.1`
- Builder:          `vite`
- User Config:      `imports`, `vite`, `alias`, `runtimeConfig`, `telemetry`, `nitro`, `app`, `css`, `modules`, `pinia`, `i18n`, `build`, `sitemap`, `robots`, `vWave`
- Runtime Modules:  `@nuxtjs/eslint-module@4.1.0`, `@nuxtjs/i18n@8.0.0-beta.13`, `@nuxt/content@2.7.2`, `nuxt-simple-sitemap@3.1.3`, `nuxt-simple-robots@3.0.3`, `@pinia/nuxt@0.4.11`, `@nuxtjs/color-mode@3.3.0`
- Build Modules:    `-`
```

**Comment by harlan-zw** [comment]
When you use the `disallow` it will only add the headers (and HTML tags if you use `defineRobotMeta()`).

To avoid cluttering the robots.txt, these weren't included by default, as you could have many disallowed routes. I've made the change to have these within the robots.txt by default within 3.1.0 though.

I'd actually recommend configuring your robots.txt with a robots.txt file though, see https://nuxtseo.com/robots/guides/robots-txt. It will handle this a lot better.

Let me know if you have any further issues.

**Comment by NtchPlayer** [comment]
Thx for your response !
