### ISSUE TITLE
How nuxt-simple-robots handle nuxt-simple-sitemap integration

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-robots#22]
### Details

Hi there, I have some interrogation about how `nuxt-simple-sitemap` is integrate with `nuxt-simple-robots` package.

[In the documentation](https://nuxtseo.com/robots/guides/default-behaviour#sitemaps), it's indicate that if we use `nuxt-simple-sitemap` package, `nuxt-simple-robots` can handle it's integration without any configuration.

So, I suppose that mean, `nuxt-simple-robots` add something like this into our `robots.txt` ?
```
Sitemap: https://my-website/sitemap.xml
```
And if we change sitemap name with [sitemapName options](https://nuxtseo.com/sitemap/api/config#sitemapname), update the property above to correspond to our custom name.

But don't see any property added to robots.txt file. So I don't know if it's a bug or if integration between packages are make differently.

I make this reproduction as an example of my use case: https://stackblitz.com/edit/nuxt-starter-zwf9ab?file=pages%2Findex.vue

**Comment by harlan-zw** [comment]
Hey @NtchPlayer, thanks for the issue :) 

By default, sitemaps aren't displayed when your site can't be indexed. When you preview your site in development, your site won't be indexed.

So for safety, you need to access your robots as `/robots.txt?indexable` to view the sitemap in development.

One thing to note is that it was showing the nitro origin by default in development, now it will default to showing your canonical site URL.

Let me know if you have any further questions..
