### ISSUE TITLE
Handle i18n locale for allow and disallow options

### ISSUE THREAD

**Issue by NtchPlayer** [harlan-zw/nuxt-simple-robots#23]
### Clear and concise description of the problem

Hi !
I know that, what I propose here is not simple to integrate and manage, but it could make this package really awesome for large site manage !

When you have a language prefix into url, we must set `allow` and `disallow` urls for every locale of our application.
So we should have something like this:
```JS
  robots: {
    allow: ['/fr$', '/en$', '/fr/information/', '/en/information/', '/en/version/', '/fr/version/'],
    disallow: ['/fr/secret$', '/en/secret$', '/fr/acount/', '/en/account/']
  }
```

### Suggested solution

Add a specific marker to handle locale prefix automatically with locales define into `nuxt/i18n`modules.

```JS
  i18n: {
    locales: [
      { code: 'en', iso: 'en-US', name: 'English' },
      { code: 'fr', iso: 'fr-FR', name: 'Français' }
    ],
    strategy: 'prefix',
    defaultLocale: 'en'
  },
  robots: {
    allow: ['/[locale]$', '/[locale]/information/', '/[locale]/version/'],
    disallow: ['/[locale]/secret$', '/[locale]/acount/']
  }
```

### Alternative

[The documentation mention that](https://nuxtseo.com/robots/guides/nuxt-config) nuxt.config can offer a programmatic control on the module options. So I don't know if we can provide a function who return array of urls with each locale ? (something like [dynamic URLs of nuxt-simple-sitemap](https://nuxtseo.com/sitemap/guides/dynamic-urls) package).

**Comment by harlan-zw** [comment]
In v3.2 it will automatically add the localised version of a path if you add the path in without the locale. This uses a similar logic to how the sitemap module works.

WIP docs below, let me know if you have any feedback on it.

---


Out of the box, the robots module will integrate directly with [@nuxtjs/i18n](https://v8.i18n.nuxtjs.org/).
You will need to use v8+ of the i18n module.

## Auto-localised Allow / Disallow

The module will automatically localise the `allow` and `disallow` paths based on your i18n configuration.

If you provide a `allow` or `disallow` path that is not localised, it will be localised for you, if your
i18n configuration allows it.

```ts [nuxt.config.ts]
export default defineNuxtConfig({
  robots: {
    disallow: ['/secret', '/admin'],
  },
  i18n: {
    locales: ['en', 'fr'],
    defaultLocale: 'en',
    strategy: 'prefix',
  }
})
```

This will generate the following output:

```txt [robots.txt]
User-agent: *
Disallow: /en/secret
Disallow: /en/admin
Disallow: /fr/secret
Disallow: /fr/admin
```

**Comment by NtchPlayer** [comment]
Nice ! I look into that after the release !
