### ISSUE TITLE
Multiple sitemap lines

### ISSUE THREAD

**Issue by dickout** [harlan-zw/nuxt-simple-robots#26]
### Details

Hello, thank you for your work!

Maybe I found an issue. Sometimes I find multiple sitemap lines, is it ok?

<img width="405" alt="image" src="https://github.com/harlan-zw/nuxt-simple-robots/assets/47948557/945707bd-b0c7-453e-b301-f9c3a6a870ad">

I think that's because I've written sitemap.xml in nuxt config, but I'm not sure.

`robots: {
sitemap: [
'/sitemap.xml'
]
}`

**Comment by harlan-zw** [comment]
Hi :) Thanks!

I was able to replicate the issue, I'm guessing you're using nuxt-simple-sitemap as well? If so, you don't need to add any config, it automatically adds it for you.

I've updated the code to dedupe the sitemaps before rendering it now though, available in v3.1.1.

**Comment by dickout** [comment]
> Hi :) Thanks!
> 
> I was able to replicate the issue, I'm guessing you're using nuxt-simple-sitemap as well? If so, you don't need to add any config, it automatically adds it for you.
> 
> I've updated the code to dedupe the sitemaps before rendering it now though, available in v3.1.1.

Great job, thank you. Yes, I'm using nuxt-simple-sitemap as well. I've tested v3.1.1, and now it's working fine on dev and prod both.
