### ISSUE TITLE
"runtimeConfig.public.siteUrl" make available

### ISSUE THREAD

**Issue by Hiratake** [harlan-zw/nuxt-simple-robots#3]
### Clear and concise description of the problem

I would like to be able to use "runtimeConfig.public.siteUrl" when specifying the sitemap URL in the "nuxt-simple-robots".
"siteUrl" is not a private value.

### Suggested solution

In "nuxt-seo-kit", uses "runtimeConfig.public.siteUrl".
https://github.com/harlan-zw/nuxt-seo-kit#1-define-config

**Comment by harlan-zw** [comment]
Hey @Hiratake 

Thank you for this issue! Have clearly overlooked this. 

Have pushed up a fix for it available in 1.0.3

**Comment by Hiratake** [comment]
Thanks for fixing this issue @harlan-zw !
