### ISSUE TITLE
Cannot restart nuxt:  fsp.statfs is not a function, after using  mergeWithRobotsTxtPath: 'assets/custom/robots.txt' 

### ISSUE THREAD

**Issue by jesspinklet** [harlan-zw/nuxt-simple-robots#35]
### Describe the bug

I'm getting an error when using mergeWithRobotsTxtPath inside my nuxt config.

![image](https://github.com/harlan-zw/nuxt-simple-robots/assets/77070946/06001bd0-3c61-425f-a6a5-185f3a7d6b0e)

  robots: {
    mergeWithRobotsTxtPath: 'assets/custom/robots.txt'
  }
  
  I was wondering if that has to do anything with newer version of nuxt or i18n.
  Is there any fix or solution for this?
  
   "nuxt": "^3.7.3",
   "nuxt-simple-robots": "^3.1.2"
   "@nuxtjs/i18n": "^8.0.0-rc.4",

**Comment by jesspinklet** [comment]
It was because of my node version 🙃, it was 18, and it fixed by changing it to 19

**Comment by harlan-zw** [comment]
Thanks, will keep this open, I should be able to fix it for Node 18
