### ISSUE TITLE
Sitemap: http://localhost/sitemap.xml is being added to robots.txt

### ISSUE THREAD

**Issue by danieldanielecki** [harlan-zw/nuxt-simple-robots#36]
### Details

Is there any extra config needed to remove the automatically added `http://localhost/sitemap.xml`?

The generated `robots.txt` looks like this:
```
# START nuxt-simple-robots (indexable)
User-agent: *
Disallow: 

Sitemap: https://doyban.com/sitemap.xml
Sitemap: http://localhost/sitemap.xml
# END nuxt-simple-robots
```

The original `robots.txt` placed in the root of the application looks like this:
```
User-agent: *
Disallow:
Sitemap: https://doyban.com/sitemap.xml
Host: https://doyban.com
```

Of course, I include the `nuxt-simple-robots` in `nuxt.config.ts` + I'm using `nuxi generate` to generate my production bundle.

**Comment by harlan-zw** [comment]
Hi @danieldanielecki, thanks for the issue.

I've tried to replicate the issue using the latest version and it seems to be working correctly, see https://stackblitz.com/edit/nuxt-starter-bj3z7q?file=public%2F_robots.txt

Can you confirm which version you're using.

**Comment by danieldanielecki** [comment]
I'm using the latest `3.1.3` in https://github.com/Doyban/Doyban-Website

**Comment by danieldanielecki** [comment]
PS. I just updated to `3.1.5` and it's fixed there :) Closing.
