### ISSUE TITLE
Lighthouse report robots.txt is not valid 

### ISSUE THREAD

**Issue by botmaster** [harlan-zw/nuxt-simple-robots#41]
### Describe the bug

Hello,
Lighthouse seems to think that my [robot.txt](https://www.pascal-achard.com/robots.txt) is not valid.
I think Lighthouse is buggy.

![CleanShot 2023-10-19 at 10 22 09](https://github.com/harlan-zw/nuxt-simple-robots/assets/488208/1c80b675-eba3-49a0-a881-cf08567c3413)

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, app, typescript, tailwindcss, colorMode, content, i18n, robots, routeRules, vite, runtimeConfig, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.5.0, @nuxtjs/color-mode@3.3.0, @nuxt/content@2.8.5, nuxt-icon@0.5.0, nuxt-headlessui@1.1.4, @nuxtjs/fontaine@0.4.1, @nuxtjs/i18n@8.0.0-rc.5, nuxt-simple-robots@3.1.6, nuxt-simple-sitemap@3.4.0, @nuxt/devtools@1.0.0
- Build Modules:    -
------------------------------
```

**Comment by botmaster** [comment]
Ok. Google Search Console validates my robots.txt 🤷‍♂️
Lighthouse is to blame.

![CleanShot 2023-10-19 at 10 31 27](https://github.com/harlan-zw/nuxt-simple-robots/assets/488208/8459d59b-5b10-482c-8423-70f5db631f6a)

**Comment by harlan-zw** [comment]
Hey, glad you could figure this out. 

I think this isn't something directly related to the module either way. It seems like you added this entry yourself? So to fix it you would just update the config to what it's asking, not sure what the module can do.

I did make an issue to explore adding validation similar to Lighthouse https://github.com/harlan-zw/nuxt-simple-robots/issues/43
