### ISSUE TITLE
`site.indexable = false` seems not to work

### ISSUE THREAD

**Issue by riddla** [harlan-zw/nuxt-simple-robots#44]
### Describe the bug

As we are building our staging environments with `process.env.NODE_ENV === 'production'` I tried to disallows all bots programmatically. This seems to work.

I cloned the repo locally and altered your `siteConfig.test.ts` as follows:

```typescript
import { describe, expect, it } from "vitest";
import { createResolver } from "@nuxt/kit";
import { setup } from "@nuxt/test-utils";

const { resolve } = createResolver(import.meta.url);

// would normally not be indexable
process.env.NODE_ENV = "production";
await setup({
  rootDir: resolve("../.playground"),
  build: true,
  server: true,
  nuxtConfig: {
    site: {
      indexable: false,
      url: "https://nuxt-simple-robots.com",
    },
    robots: {
      sitemap: ["/sitemap.xml"],
    },
  },
});

describe("siteConfig", () => {
  it("disables", async () => {
    const robotsTxt = await $fetch("/robots.txt");
    // the site.url should be appended
    expect(
      robotsTxt.includes("Sitemap: https://nuxt-simple-robots.com/sitemap.xml")
    ).toBe(true);
    // site.indexable should be honoured
    expect(robotsTxt.includes("(indexable)")).toBe(false);
  });
});
```

The test fails, but as I did only fiddle with it for a few minutes, it might be a false negative.

(Thanks a ton for your great SEO modules, they are much appreciated!)

### System / Nuxt Info

- Operating System: `Darwin`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `-`
- User Config:      `experimental`, `nitro`, `imports`, `hooks`, `css`, `vue`, `vite`, `modules`, `i18n`, `devtools`, `typescript`, `site`, `sitemap`, `runtimeConfig`, `image`, `locales`
- Runtime Modules:  `@nuxt/devtools@0.7.6`, `@nuxtjs/tailwindcss@6.8.0`, `@nuxt/content@2.8.5`, `@nuxt/image@1.0.0`, `nuxt-schema-org@3.0.1`, `nuxt-simple-sitemap@3.4.0`, `nuxt-simple-robots@3.1.6`, `nuxt-typed-router@3.3.1`, `@tricks-gmbh/add-custom-route-paths-to-nuxt-i18n@0.1.25`, `@nuxtjs/i18n@8.0.0-rc.5`, `@tricks-gmbh/nuxt-use-trailings-slashes@0.1.14`
- Build Modules:    `-`

**Comment by harlan-zw** [comment]
Hi @riddla, thank you for the kind words and issue.

Seems to be a bug with nuxt-site-config, I pushed up a fix and it's in the latest nuxt-simple-robots. Can you try the latest version and let me know how it goes?

**Comment by riddla** [comment]
This does work now, thanks a lot!

Only thing that confuses me: the comment within the robots.txt says `(indexable)`, although the site is not respectively `Disallow: /` is set. Or am I reading it wrong?

![Screenshot 2023-10-30 at 07 50 41](https://github.com/harlan-zw/nuxt-simple-robots/assets/174157/977dd48e-ccf8-404f-b218-8e1178266fa7)

**Comment by harlan-zw** [comment]
Hmm interesting, the only way I can see that you achieved this was by providing robot rules that disable the indexing (instead of using the `indexable` site config).

I've pushed out some improvements for detecting that, could you try out 3.1.9 :pray: If the issue persists could you provide some reproduction details.

**Comment by riddla** [comment]
My bad and you're right: I left a snippet within my `nuxt.config.ts` that I used before to manually disable the indexing:

```javascript
  robots: {
    enabled: true,
    disallow: isProductionEnvironment ? '' : '/',
    debug: true,
  },
```

Unfortunately even with `v3.1.9` and the following config the site is still indexable:

```javascript
  site: {
    url: baseUrl,
    trailingSlash: true,
    indexable: false,
  },

  robots: {
    enabled: true,
    debug: true,
  },
```

```
# START nuxt-simple-robots (indexable)
User-agent: *
Disallow: 

Sitemap: http://fach-static:81/sitemap.xml
# END nuxt-simple-robots
```

**Comment by harlan-zw** [comment]
I think I'll need some help reproducing this if you have the capacity, you can use the [Stackblitz starter](https://stackblitz.com/edit/nuxt-starter-zycxux?file=public%2F_robots.txt).

The test I have with this config seems to be passing.

```ts
import { describe, expect, it } from 'vitest'
import { setup } from '@nuxt/test-utils'
import { createResolver } from '@nuxt/kit'

const { resolve } = createResolver(import.meta.url)

process.env.NODE_ENV = 'production'
await setup({
  rootDir: resolve('../.playground'),
  build: true,
  nuxtConfig: {
    site: {
      url: 'https://example.com',
      trailingSlash: true,
      indexable: false,
    },

    robots: {
      enabled: true,
      debug: true,
    },
  },
})

describe('nonIndexable', () => {
  it('basic', async () => {
    expect(await $fetch('/robots.txt')).toMatchInlineSnapshot(`
      "# START nuxt-simple-robots (indexing disabled)
      User-agent: *
      Disallow: /

      # END nuxt-simple-robots"
    `)
  })
})
```

**Comment by riddla** [comment]
Well, this must have been just a glitch within my packages respectively versions – after some fiddling (and deleting lock files) everything seems to work now.

Thanks a lot!
