### ISSUE TITLE
How can I adjust the indexable parameter at runtime using the nuxt-simple-robots module?

### ISSUE THREAD

**Issue by dhondtlaurens** [harlan-zw/nuxt-simple-robots#46]
### Details

How can I dynamically set the indexable parameter during runtime for my project using the `nuxt-simple-robots`, `nuxt-simple-sitemap`, and `nuxt-site-config` modules? The documentation suggests using the site config to configure the indexable option, but I'm encountering difficulties in changing its value during runtime through the `updateSiteConfig` composable. I've attempted various approaches, including using plugins and hooks, but none of them appear to be effective. Could you provide guidance on how to achieve this by utilizing an environment variable?

**Comment by DavidDeSloovere** [comment]
What would your criteria be to enable of disable at runtime? 

Current hostname would be one thing I can come up with (ie index `sitename.com` and not `sitename.pages.dev`). If that is supported out of the box.

**Comment by harlan-zw** [comment]
This one is on my radar and will look to solve either with some code or documentation soon.

**Comment by harlan-zw** [comment]
I've released rc for v4 which improves the documentation and API around this.

See the following docs:
- [Disabling Indexing](https://nuxtseo.com/robots/guides/disable-indexing)
- [Runtime Site Config](https://nuxtseo.com/site-config/guides/runtime-site-config)

Please let me know if there are areas that can be improved or if you still have issues.
