### ISSUE TITLE
`sitemap` actually defaults to `/sitemap.xml` ?

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-simple-robots#5]
### Details

It seems to be the case when simply adding `nuxt-simple-robots` in `modules` and not putting any `robots` section in `nuxt.config.ts`. Do you confirm?

```
# START nuxt-simple-robots (indexable: true)
# This is a development preview
User-agent: *
Disallow: 

Sitemap: /sitemap.xml
# END nuxt-simple-robots
```

**Comment by harlan-zw** [comment]
Hey @tmlmt 

If you're using the [nuxt-simple-sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap) module or Nuxt SEO Kit it automatically adds these entries for you.

If you're not using these would it be possible to create a reproduction? I can't replicate

**Comment by tmlmt** [comment]
Hi @harlan-zw, thanks for reverting and pointing me to the reason: I'm indeed using `nuxt-simple-sitemap`. It's indeed indicated in the [nuxt-simple-sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap#zero-config-integrations) 🙈. Just a suggestion then, to add something similar in this repo's README :) Thanks again.

**Comment by harlan-zw** [comment]
> Hi @harlan-zw, thanks for reverting and pointing me to the reason: I'm indeed using `nuxt-simple-sitemap`. It's indeed indicated in the [nuxt-simple-sitemap](https://github.com/harlan-zw/nuxt-simple-sitemap#zero-config-integrations) see_no_evil. Just a suggestion then, to add something similar in this repo's README :) Thanks again.

Agreed, have updated the docs
