### ISSUE TITLE
How the environments works?

### ISSUE THREAD

**Issue by abdonrd** [harlan-zw/nuxt-simple-robots#51]
### Details

In the docs:
https://nuxtseo.com/robots/guides/default-behaviour#non-production-environments

We can see this:
> A non-production environment is any environment that has `process.env.NODE_ENV !== 'production'`.

But in the Nuxt docs:
https://nuxt.com/docs/api/commands/build

> This command sets `process.env.NODE_ENV` to `production`.

Thanks!

**Comment by harlan-zw** [comment]
Thanks for the issue, this is something I need to make clearer in the docs.

This is the current recommended solution https://nuxtseo.com/site-config/guides/setting-site-config#environment-specific-site-config

**Comment by abdonrd** [comment]
If we use the environment context, we see type errors:

<img width="813" alt="Screenshot 2023-11-29 at 10 18 14 AM" src="https://github.com/harlan-zw/nuxt-simple-robots/assets/1007051/22244f27-e13c-4255-b532-59b158a553f6">

**Comment by harlan-zw** [comment]
Hi, please see the updated docs.

See the following docs:
- [Disabling Indexing](https://nuxtseo.com/robots/guides/disable-indexing)
- [Environment Specific Config](https://nuxtseo.com/site-config/guides/setting-site-config#environment-specific-site-config)

Let me know if it's still not clear.
