### ISSUE TITLE
robots.txt keeps indexable false

### ISSUE THREAD

**Issue by leonardo-melhor-envio** [harlan-zw/nuxt-simple-robots#53]
### Describe the bug

i'm trying to add the pages that should not be indexed, but alway the robots is generated like this:

``` bash
# START nuxt-simple-robots (indexing disabled)
User-agent: *
Disallow: /

# END nuxt-simple-robots
```

this is my config:

```javascript
export const robots = {
  siteUrl: process.env.NUXT_PUBLIC_SITE_URL,
  indexable: true
  sitemap: '/sitemap.xml',
  disallow: ['/ffs', '/admin-panel'],
  allow: ['/login', '/register', '/terms', '/support']
}
```

in  nuxt.config i use the static generation mode.

**Comment by leonardo-melhor-envio** [comment]
i had a _robots.txt file at ```/public``` folder, and for reason it had blocked the new generation.

**Comment by harlan-zw** [comment]
And just to confirm the _robots.txt file you had was blocking indexing? The recommendation is to use this file for production robot.txt data

**Comment by leonardo-melhor-envio** [comment]
@harlan-zw i confirm that, _robots.txt in public folder was blocking the indexing.
