### ISSUE TITLE
Allows for dynamically merging raw robots.txt content at runtime

### ISSUE THREAD

**Issue by everyx** [harlan-zw/nuxt-simple-robots#54]
### Clear and concise description of the problem

I have a website and user can change `robots.txt` at backend,  it's a raw robots.txt, and we should merge it with default generated by `nuxt-simple-robots`, I don't have a structured robots config, so it's difficult to do this.

### Suggested solution

Maybe a new config option: `mergeWithRobotsTxt`, so I can pass a raw robots.txt content with it.

**Comment by harlan-zw** [comment]
Hi @everyx 

I'm not sure if there's a way that this module can provide a simple solution for this, but it can provide you with all of the pieces needed to get it working yourself.

In v4 the module exports a `util` subpath with all of the core functions, this provides `parseRobotsTxt` to convert a raw robots.txt into a parsed object that you can merge with the main config

```ts
import { parseRobotsTxt } from 'nuxt-simple-robots/util'

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('robots:context', async (ctx) => {
    if (ctx.context === 'robots.txt') {
      // TODO do your fetch or whatever
      const robotsTxt = parseRobotsTxt(`
User-agent: *
Disallow: /api/
      `)
      ctx.sitemaps.push(...robotsTxt.sitemaps)
      ctx.groups.push(...robotsTxt.groups)
    }
  })
})
```

Let me know if you have any questions on this, I don't think there's anything else I can do on my end.
