### ISSUE TITLE
Robots meta tag is not injected

### ISSUE THREAD

**Issue by michalzaq12** [harlan-zw/nuxt-simple-robots#68]
### Describe the bug

The Robots meta tag is not injected into SPA pages when building with: `nuxt generate`.
For pre-rendered pages, the tag works well.

Nuxt config:
```js
ssr: true,
routeRules: {
    '/spa': { ssr: false } // or  { ssr: false, robots: false / true }
}
```

### System / Nuxt Info

```Shell
"nuxt": "^3.9.1",
"nuxt-simple-robots": "^4.0.0-rc.12"
```

**Comment by harlan-zw** [comment]
Thanks, this should be fixed in 4.0.0-rc.13.
