### ISSUE TITLE
Invalid robots roule

### ISSUE THREAD

**Issue by michalzaq12** [harlan-zw/nuxt-simple-robots#69]
### Describe the bug

The module does not support "named route" from radix3 and produces an incorrect rule.

Nuxt config:
```js
routeRules: {
'/integration/:name': { robots: false },
}
```

Generated robots.txt
```
User-agent: *
Disallow: 
Disallow: /integration/:name
```

Should be:
```
User-agent: *
Disallow: 
Disallow: /integration/*
```

### System / Nuxt Info

```Shell
"nuxt": "^3.9.1",
"nuxt-simple-robots": "^4.0.0-rc.12"
```

**Comment by harlan-zw** [comment]
Thanks for this one too :) Available in rc.13
