### ISSUE TITLE
Provide an absolute URL for `sitemap`

### ISSUE THREAD

**Issue by tmlmt** [harlan-zw/nuxt-simple-robots#7]
### Clear and concise description of the problem

SEO score on Lighthouse is decreased because the provided sitemap is not an absolute URL:
![image](https://user-images.githubusercontent.com/10244927/226770541-964b1e3f-2caf-4522-831d-a1f96f6c5db2.png)

### Suggested solution

As suggested [here](https://developer.chrome.com/docs/lighthouse/seo/invalid-robots-txt/?utm_source=lighthouse&utm_medium=lr#provide-an-absolute-url-for-sitemap):

![image](https://user-images.githubusercontent.com/10244927/226770624-7b6784e1-a933-422e-8c02-238431c91b1d.png)

### Alternative

-

### Additional context

I am using nuxt-simple-sitemap in addition to nuxt-simple-robots

**Comment by harlan-zw** [comment]
Did you provide a siteUrl?

This is a bug if so 🤔

**Comment by tmlmt** [comment]
I have, as `process.env.NUXT_PUBLIC_SITE_URL`
See repro: https://stackblitz.com/edit/nuxt-starter-gmr2r8?file=.env

**Comment by harlan-zw** [comment]
This seems to be fixed in 2.1.0, see https://stackblitz.com/edit/nuxt-starter-titwf9?file=nuxt.config.ts

Running with `NUXT_PUBLIC_SITE_URL=https://example.com nuxi dev`
