### ISSUE TITLE
Check for hint: "You have a disallow rule with `/` which blocks all routes." is potentially wrong.

### ISSUE THREAD

**Issue by ghost** [harlan-zw/nuxt-simple-robots#71]
### Describe the bug

When managing multiple groups, if a group contains the rule "Disallow: /," you'll receive the message:

> You have a disallow rule with `/` which blocks all routes

and the indexable flag will be set to false, even if there are multiple defined groups.

An example of a valid robots.txt file that should be indexable:

```js
{
  userAgent: ['*'],
  disallow: ['/'],
},
{
  userAgent: ['Twitterbot', 'facebookexternalhit'],
  allow: ['/images'],
},
```

See: https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt#:~:text=Allow%20access%20to%20a%20single%20crawler

Additionally, the order of the disallow and allow directives should not impact the outcome, see: https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt#:~:text=Disallow%20crawling%20of%20an%20entire%20site%2C%20but%20allow%20Mediapartners%2DGoogle 

I believe the check at https://github.com/harlan-zw/nuxt-simple-robots/blob/730c92b8c1b02d478cf5c020fdb183bb9df59964/src/runtime/nitro/composables/getSiteRobotConfig.ts#L14  is incorrect, and the mentioned hint should only be displayed if there is a single group with "disallow: /".

### Reproduction

https://stackblitz.com/edit/github-73uxeq?file=app.vue

**Comment by harlan-zw** [comment]
If you're only allowing access to your site to a specific crawler I would consider the site to not be indexable generally. I think providing any other logic is confusing for the end user and module integrations.

Is the only issue you're looking to solve is to not have this development hint displayed?

**Comment by ghost** [comment]
I overlooked that `?mockProductionEnv` exists as the development hint is different when site > indexable is set to true. 

I've updated the repro to use side.indexable: true, so you can see that there is now the hint missing regarding the `?mockProductionEnv`
 
```
  // nuxt.config.js
 
  site: {
    indexable: true
  },
```
 
```
# START nuxt-simple-robots (indexing disabled)
User-agent: *
Disallow: /
 
# DEVELOPMENT HINTS: You have a disallow rule with `/` which blocks all routes., Indexing is blocked by site config set by nuxt-site-config:config.
 
# END nuxt-simple-robots
```
"**Indexing is blocked by site config set by nuxt-site-config:config.**"
 
With `indexable: true` the sitemap states that indexing is disabled and furthermore even blocked by the site config set which seems wrong to me as I clearly say that the page should be indexable. 🤔 I initially set indexable to true as I wanted to conditionally set it once the robots.txt is configured to my liking depending on where the project is being deployed at.
 
===
 
As the repro doesn't have site > indexable set I tried it there as well.
 
Without `?mockProductionEnv`
```
# START nuxt-simple-robots (indexing disabled)
User-agent: *
Disallow: /
# DEVELOPMENT HINTS: You have a disallow rule with `/` which blocks all routes., Indexing is blocked because of the environment. You can mock a production environment with ?mockProductionEnv query.
# END nuxt-simple-robots
```
With `?mockProductionEnv`
```# START nuxt-simple-robots (indexable)
User-agent: *
Disallow: /
User-agent: Twitterbot
User-agent: facebookexternalhit
Allow: /images
User-agent: SemrushBot
User-agent: SiteAuditBot
User-agent: Seobility
Allow: /
# DEVELOPMENT HINTS: You have a disallow rule with `/` which blocks all routes., You are mocking a production enviroment with ?mockProductionEnv query.
# END nuxt-simple-robots
```

So I am not sure if this is a bug regarding setting site.indexable: true which hides the hint about the `?mockProductionEnv` but thanks for the answer, I was now able to figure everything out and I am able to implement my robots.txt

**Comment by harlan-zw** [comment]
Thanks for the details. I have pushed up a couple of changes to improve this:
1. site-wide indexing is no longer disabled if you have a wild card disallow with other robot groups
2. dev hints have been improved to make these things more obvious and handle more edge cases

For 1, headers and meta tags are still applied to these `Allowed` paths, if bots also respect this, then they may be broken? What do you think would be the best way to handle this?
