### ISSUE TITLE
Provide an alternative for NUXT_SITE_ENV variable

### ISSUE THREAD

**Issue by Seanitzel** [harlan-zw/nuxt-simple-robots#77]
### Clear and concise description of the problem

Thank you for this great module!
A proposal:
Currently it seems like the only way to disable indexing for testing environments is by setting NUXT_SITE_ENV to something different than production.
As stated [here](https://nuxtseo.com/robots/guides/disable-indexing)

### Suggested solution

I would like another way to do it within the nuxt.config file.
e.g
```ts
import config from './config';

export default defineNuxtConfig({
  seo: {
    notProduction: config.isProd
    },
    ....
  }
  ```
  
  The config file can may use other environment variables to determine whether it is prod or not.
  e.g in my case I will use `FIREBASE_ENV`

### Additional context

I think it's not the best DX to force us to add an env variable for this plugin.

**Comment by harlan-zw** [comment]
You can provide config through nuxt.config already:

```ts
export default defineNuxtConfig({
  site: {
    // indexable is false when env != 'production', but you can manually override it as well
    indexable: config.isProd,
    // set however you want
    env: config.isProd ? 'production' : 'staging'
  }
})
```

You can override it using environment variables if needed. They are just easier for most people out of the box.
