### ISSUE TITLE
Please advise on how to set rules for different roles

### ISSUE THREAD

**Issue by zhangjunjie6b** [harlan-zw/nuxt-simple-robots#8]
### Details

User-agent: Baidu
Disallow: /aa.html
Disallow: /bb.html

User-agent: Sogou
Disallow: /aa.html
Disallow: /bb.html

User-agent: 360Spider
Disallow: /aa.html
Disallow: /bb.html

User-agent: YisouSpider
Disallow: /aa.html
Disallow: /bb.html

User-agent: YoudaoBot
Disallow: /aa.html
Disallow: /bb.html

User-agent: *
Allow: /

**Comment by harlan-zw** [comment]
Hey @zhangjunjie6b 

Your best option would be to use the nitro hook: https://github.com/harlan-zw/nuxt-simple-robots#robotsrobots-txt

Let me know if you have any issues

**Comment by zhangjunjie6b** [comment]
I understand. Thank you
