### ISSUE TITLE
Cache Nitro's route matcher between requests.

### ISSUE THREAD

**Issue by KyleSmith0905** [harlan-zw/nuxt-simple-robots#81]
### Details

I received feedback from a @sidebase/nuxt-auth contributor on a pull request I submitted. They recommended caching the Nitro route rules as to not create a Nitro router on every request. I had not once considered that and it makes tons of sense now.

The pull request in @sidebase/nuxt-auth: https://github.com/sidebase/nuxt-auth/pull/610#discussion_r1525164774

Since I pulled the code from you, I would like to pass up that suggestion.

The code I pulled from you: https://github.com/harlan-zw/nuxt-simple-robots/blob/main/src/runtime/nitro/kit.ts

**Comment by harlan-zw** [comment]
Thanks, this seems like a sensible thing to do, the performance cost should be quite negligible though.

I've pushed up a fix to store the context on the Nitro app. Btw this function exists within this module to solve trailing slash issues. I'm not sure if a more recent Nitro version has fixed the problem.
